/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateCard: typeof import('./src/components/CountDown/animateCard.vue')['default']
    AnimateClock: typeof import('./src/components/CountDown/animateClock.vue')['default']
    BaseScrollList: typeof import('./src/components/BaseScrollList.vue')['default']
    Block: typeof import('./src/components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./src/components/breadcrumb/index.vue')['default']
    CarouselF: typeof import('./src/components/Carousel-f.vue')['default']
    Chart: typeof import('./src/components/chart/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    FooterView: typeof import('./src/components/TodoList/components/FooterView.vue')['default']
    FormWrapper: typeof import('./src/components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default']
    HeaderView: typeof import('./src/components/TodoList/components/HeaderView.vue')['default']
    ItemVue: typeof import('./src/components/TodoList/components/ItemVue.vue')['default']
    List: typeof import('./src/components/message-box/list.vue')['default']
    ListView: typeof import('./src/components/TodoList/components/ListView.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MessageBox: typeof import('./src/components/message-box/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    OrderMap: typeof import('./src/components/orderMap.vue')['default']
    OrderMap111: typeof import('./src/components/orderMap111.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesList: typeof import('./src/components/SalesList/index.vue')['default']
    Sign: typeof import('./src/components/sign/index.vue')['default']
    TodoList: typeof import('./src/components/TodoList/index.vue')['default']
    UploadImg: typeof import('./src/components/uploadImg/uploadImg.vue')['default']
  }
}
