/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateCard: typeof import('./src/components/CountDown/animateCard.vue')['default']
    AnimateClock: typeof import('./src/components/CountDown/animateClock.vue')['default']
    BaseScrollList: typeof import('./src/components/BaseScrollList.vue')['default']
    Block: typeof import('./src/components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./src/components/breadcrumb/index.vue')['default']
    CarouselF: typeof import('./src/components/Carousel-f.vue')['default']
    Chart: typeof import('./src/components/chart/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    FormWrapper: typeof import('./src/components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default']
    List: typeof import('./src/components/message-box/list.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MessageBox: typeof import('./src/components/message-box/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    OrderMap: typeof import('./src/components/orderMap.vue')['default']
    OrderMap111: typeof import('./src/components/orderMap111.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesList: typeof import('./src/components/SalesList/index.vue')['default']
    Sign: typeof import('./src/components/sign/index.vue')['default']
    UploadImg: typeof import('./src/components/uploadImg/uploadImg.vue')['default']
  }
}
